version: "3.8"

services:
  db:
    image: mongo:latest
    volumes:
      - slack_db:/data/db
    ports:
      - "27017:27017"
    networks:
      - app_network  # Attach to a common network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5500:5500"
    environment:
      - CONNECTION=mongodb://db:27017/todo-app  # Use db hostname, which is the service name
    depends_on:
      - db
    networks:
      - app_network  # Attach to the same network

  frontend:
    build:
      context: ./Frontend/todolist
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app_network  # Attach to the same network

volumes:
  slack_db: {}

networks:
  app_network:  # Define a common network
    driver: bridge  # Using the default bridge network
